-- Insert STL modules
INSERT INTO modules (id, title, description, category, content, files, order_index, is_active) VALUES
('550e8400-e29b-41d4-a716-446655440001', 'STL ZODÍACO', 'Modelos 3D dos signos do zodíaco', 'ARQUIVOS STL', 'Coleção completa de modelos 3D dos 12 signos do zodíaco, perfeitos para impressão 3D. Cada modelo foi cuidadosamente projetado com detalhes únicos.', '["aries.stl", "touro.stl", "gemeos.stl", "cancer.stl", "leao.stl", "virgem.stl", "libra.stl", "escorpiao.stl", "sagitario.stl", "capricornio.stl", "aquario.stl", "peixes.stl"]', 1, true),
('550e8400-e29b-41d4-a716-446655440002', 'STL DESENHOS GERAIS', 'Modelos 3D diversos e criativos', 'ARQUIVOS STL', 'Uma variedade de modelos 3D para diferentes propósitos: decoração, utilitários, arte e muito mais.', '["vaso_decorativo.stl", "porta_canetas.stl", "chaveiro_personalizado.stl", "miniatura_casa.stl", "escultura_abstrata.stl"]', 2, true),
('550e8400-e29b-41d4-a716-446655440003', 'STL MINI MUNDO', 'Miniaturas de cenários e mundos', 'ARQUIVOS STL', 'Crie seu próprio mini mundo com estas miniaturas detalhadas de casas, árvores, carros e personagens.', '["casa_miniatura.stl", "arvore_pequena.stl", "carro_mini.stl", "pessoa_miniatura.stl", "banco_praca.stl"]', 3, true),
('550e8400-e29b-41d4-a716-446655440004', 'STL RPG', 'Modelos para jogos de RPG', 'ARQUIVOS STL', 'Miniaturas de personagens, monstros e acessórios para seus jogos de RPG de mesa.', '["guerreiro.stl", "mago.stl", "dragao.stl", "orc.stl", "elfo.stl", "dados_personalizados.stl"]', 4, true),
('550e8400-e29b-41d4-a716-446655440005', 'STL PERSONALIDADES E CELEBRIDADES', 'Bustos e figuras de personalidades', 'ARQUIVOS STL', 'Modelos 3D de personalidades históricas e celebridades para coleção e decoração.', '["einstein_busto.stl", "da_vinci.stl", "shakespeare.stl", "frida_kahlo.stl"]', 5, true),
('550e8400-e29b-41d4-a716-446655440006', 'STL CENÁRIOS', 'Cenários e ambientes 3D', 'ARQUIVOS STL', 'Cenários completos para dioramas, jogos e exposições. Desde paisagens naturais até ambientes urbanos.', '["montanha_cenario.stl", "cidade_futurista.stl", "floresta_magica.stl", "praia_tropical.stl"]', 6, true),
('550e8400-e29b-41d4-a716-446655440007', 'STL RELIGIÃO URBANA', 'Modelos de elementos religiosos urbanos', 'ARQUIVOS STL', 'Elementos arquitetônicos e decorativos inspirados na religiosidade urbana contemporânea.', '["cruz_moderna.stl", "anjo_urbano.stl", "mandala_3d.stl", "simbolo_paz.stl"]', 7, true);

-- Create admin user profile (will be created when admin signs up)
-- This is just for reference, actual profile will be created via trigger
